trigger:
- none

pool: azure_agent_pool
  
variables:
  # --- Temel Tarama Bilgileri ---
  # WebInspect'in tarayacagi hedef URL.
  webinspect.targetUrl: 'http://zero.webappsecurity.com/'
  
  # Taramanın adi. Diger tüm yollar ve SSC projesi bu isme göre olusturulacaktir.
  webinspect.scanName: 'ZeroWebApp-Guvenlik-Taramasi'
  
  # Tarama icin kullanılacak makro dosyasinin tam yolu.
  webinspect.macroPath: 'C:\zeroirfan.webmacro'

  # --- Fortify SSC Baglanti Bilgileri ---
  ssc.url: 'http://192.168.13.177:8080/ssc'
  ssc.authToken: 'e04bd46e-2073-4a7b-8d87-04042fa652b3'
  
  # (.fpr) dosyasinin yolu, scanName'e gore otomatik oluşturulur.
  webinspect.reportPath: 'C:\Windows\Temp\$(webinspect.scanName).fpr'
  
  # Log dosyasinin yolu, C:\temp altinda ve scanName'e gore olusturulur.
  webinspect.logPath: 'C:\Windows\Temp\$(webinspect.scanName)_log.txt'
  
  ssc.projectName: 'wi test'
  
  ssc.projectVersion: 'witestwithclient'


steps:  
- task: PowerShell@2
  displayName: 'WebInspect Taramasını Başlat'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "WebInspect taramasi baslatiliyor..."
      Write-Host "Hedef URL: $(webinspect.targetUrl)"
      Write-Host "Tarama Adi: $(webinspect.scanName)"
      Write-Host "Rapor Dosyasi: $(webinspect.reportPath)"
      Write-Host "Log Dosyasi: $(webinspect.logPath)"
      
      # Degiskenler kullanilarak komut calistiriliyor
      & "C:\Program Files\Fortify\Fortify WebInspect\WI.exe" -u "$(webinspect.targetUrl)" -n "$(webinspect.scanName)" -macro "$(webinspect.macroPath)" -ep "$(webinspect.reportPath)" -v | Tee-Object -FilePath "$(webinspect.logPath)"

      Write-Host "WebInspect islemi tamamlandi. Cikis Kodu: $LASTEXITCODE"
      
      if ($LASTEXITCODE -ne 0) {
        Write-Error "WebInspect taramasi basarisiz oldu! Cikis Kodu: $LASTEXITCODE"
        exit 1
      }

- task: PowerShell@2
  displayName: 'Log Dosyasında Kritik Hataları Kontrol Et'
  condition: succeeded()
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)/test.ps1'
    
    # Argumanlar, otomatik olusturulan 'webinspect.logPath' degiskenini kullaniyor.
    arguments: '-InitialLogPath "$(webinspect.logPath)" -ErrorsFilePath "$(System.DefaultWorkingDirectory)/hatalar.txt"'
    
    errorActionPreference: 'stop'


- task: CmdLine@2
  displayName: 'Fortify SSC ye FPR Yükle'
  condition: succeeded()
  inputs:
    script: |
      echo Hata bulunmadi. FPR dosyasi Fortify SSC'ye yukleniyor...
      
      fortifyclient -url "$(ssc.url)" -authtoken "$(ssc.authToken)" uploadFPR -file "$(webinspect.reportPath)" -project "$(ssc.projectName)" -version "$(ssc.projectVersion)"