trigger:
- main
 
pool: Default

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '& "wi.exe" -u http://zero.webappsecurity.com/ -n "azuretest2" -macro "C:\zeroirfan.webmacro" -ep "C:\raporlar2\testazure2.fpr" -v | Tee-Object -FilePath C:\log2.txt'
    workingDirectory: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'


