
trigger:
- main

pool: azure_agent_pool

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '& "C:\Program Files\Fortify\Fortify WebInspect\WI.exe" -u http://zero.webappsecurity.com/ -n "azuretest2" -macro "C:\zeroirfan.webmacro" -ep "C:\raporlar2\testazure2.fpr" -v | Tee-Object -FilePath "C:\Users\Administrator\Desktop\log.txt"'



