trigger:
- main

pool: azure_agent_pool

steps:

# ADIM 1: WebInspect Taramasını Başlat
# Bu adım, taramayı yapar ve "C:\raporlar2\testazure2.fpr" dosyasını oluşturur.
- task: PowerShell@2
  displayName: 'WebInspect Taramasını Başlat'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "WebInspect taraması başlatılıyor..."
      $process = Start-Process -FilePath "C:\Program Files\Fortify\Fortify WebInspect\WI.exe" -ArgumentList '-u http://zero.webappsecurity.com/ -n "azuretestirfa" -macro "C:\zeroirfan.webmacro" -ep "C:\raporlar2\testazureirfan.fpr" -v' -Wait -PassThru
      
      $process.StandardOutput | Tee-Object -FilePath "C:\Users\Administrator\Desktop\log.txt"
      
      Write-Host "WebInspect işlemi tamamlandı. Çıkış Kodu: $($process.ExitCode)"
      
      if ($process.ExitCode -ne 0) {
        Write-Error "WebInspect taraması başarısız oldu!"
        exit 1
      }

# ADIM 2: Python Hata Kontrol Script'ini Çalıştır (KAPI BEKÇİSİ GÖREVİ)
# Bu adım başarısız olursa (hata bulunursa), pipeline burada durur.
- script: |
    python --version
    python kontrol_scripti.py
  displayName: 'WebInspect Log Hata Kontrolünü Çalıştır'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# ADIM 3: FPR Dosyasını Fortify SSC'ye Yükle (YENİ ADIM)
# Bu adım SADECE 2. Adım başarılı olursa çalışır.
- task: CmdLine@2
  displayName: 'Fortify SSC ye FPR Yükle'
  inputs:
    script: |
      echo Hata bulunmadı. FPR dosyası Fortify SSC'ye yükleniyor...
      
      rem ÖNEMLİ: "-file" parametresinin WebInspect'in oluşturduğu gerçek dosyayı gösterdiğinden emin olun.
      fortifyclient -url http://192.168.13.177:8080/ssc -authtoken $(FORTIFY_AUTH_TOKEN) uploadFPR -file "C:\raporlar2\testazureirfan.fpr" -project "wi test" -version "witestwithclient"